// tools/registry.js
// Catalogo central do ArqKit. Status "ready" significa rota funcional hoje.
// Ferramentas planejadas aparecem como "coming-soon" para nao simular fluxos.

export const CATEGORIES = [
  { id: "all", name: "Todas", icon: "grid" },
  { id: "popular", name: "Mais usadas", icon: "star" },
  { id: "pdf", name: "PDF", icon: "file-text" },
  { id: "images", name: "Imagens", icon: "image" },
  { id: "video", name: "Video", icon: "video" },
  { id: "audio", name: "Audio", icon: "audio" },
  { id: "documents", name: "Documentos", icon: "document" },
  { id: "security", name: "Seguranca", icon: "shield" },
  { id: "ocr", name: "OCR", icon: "search" },
];

export const STATUS_META = {
  ready: { label: "Pronta", badge: "Pronta", className: "is-ready" },
  beta: { label: "Beta", badge: "Beta", className: "is-beta" },
  "coming-soon": { label: "Em breve", badge: "Em breve", className: "is-soon" },
};

export const TOOLS = [
  {
    id: "compress",
    name: "Comprimir PDF",
    shortName: "Comprimir",
    description: "Reduza o tamanho do PDF mantendo boa qualidade.",
    tooltip: "Comprima imagens e scans dentro do PDF direto no navegador.",
    categoryIds: ["pdf"],
    aliases: ["comprimir", "compactar", "reduzir", "diminuir", "compress", "compressao", "otimizar pdf"],
    keywords: ["pdf", "leve", "tamanho", "email", "arquivo menor", "compressor"],
    inputExtensions: ["pdf"],
    outputExtensions: ["pdf"],
    route: "./comprimir-pdf.html#tool=compress",
    icon: "file-zip",
    color: "red",
    status: "ready",
    supportsBatch: false,
    isLocalFirst: true,
    isPopular: true,
    isQuickAction: true,
    notes: [],
  },
  {
    id: "merge",
    name: "Juntar PDF",
    shortName: "Juntar",
    description: "Una varios PDFs em um unico arquivo.",
    tooltip: "Junte PDFs na ordem escolhida, sem enviar arquivos para servidor.",
    categoryIds: ["pdf"],
    aliases: ["juntar", "unir", "mesclar", "merge", "combinar", "combine"],
    keywords: ["pdf", "varios arquivos", "documentos", "ordem"],
    inputExtensions: ["pdf"],
    outputExtensions: ["pdf"],
    route: "./comprimir-pdf.html#tool=merge",
    icon: "link",
    color: "purple",
    status: "ready",
    supportsBatch: true,
    isLocalFirst: true,
    isPopular: true,
    isQuickAction: true,
    notes: [],
  },
  {
    id: "merge_then_compress",
    name: "Juntar e comprimir PDF",
    shortName: "Juntar + comprimir",
    description: "Una varios PDFs e reduza o tamanho ao mesmo tempo.",
    tooltip: "Gere um PDF unico e comprimido em uma operacao local.",
    categoryIds: ["pdf"],
    aliases: ["juntar e comprimir", "unir e comprimir", "merge and compress", "combinar e reduzir"],
    keywords: ["pdf", "compressao", "unir", "arquivo unico"],
    inputExtensions: ["pdf"],
    outputExtensions: ["pdf"],
    route: "./comprimir-pdf.html#tool=merge_then_compress",
    icon: "puzzle",
    color: "green",
    status: "ready",
    supportsBatch: true,
    isLocalFirst: true,
    isPopular: true,
    notes: [],
  },
  {
    id: "split",
    name: "Dividir PDF",
    shortName: "Dividir",
    description: "Extraia paginas ou divida seu PDF em varios arquivos.",
    tooltip: "Separe paginas, intervalos ou blocos de um PDF localmente.",
    categoryIds: ["pdf"],
    aliases: ["dividir", "separar", "split", "partir", "fatiar", "extrair paginas"],
    keywords: ["pdf", "paginas", "intervalos", "organizar"],
    inputExtensions: ["pdf"],
    outputExtensions: ["pdf", "zip"],
    route: "./dividir.html",
    icon: "split",
    color: "orange",
    status: "ready",
    supportsBatch: false,
    isLocalFirst: true,
    isPopular: true,
    notes: [],
  },
  {
    id: "camera-to-pdf",
    name: "Camera para PDF",
    shortName: "Camera PDF",
    description: "Fotografe documentos ou importe imagens e gere um PDF.",
    tooltip: "Capture paginas pelo celular ou importe imagens para montar um PDF.",
    categoryIds: ["images", "documents"],
    aliases: ["camera", "camera", "foto para pdf", "scan", "scanner", "digitalizar", "documento para pdf", "camera to pdf"],
    keywords: ["celular", "foto", "imagem", "documento", "scan"],
    inputExtensions: ["jpg", "jpeg", "png", "webp", "heic"],
    outputExtensions: ["pdf"],
    route: "./camera.html",
    icon: "camera",
    color: "blue",
    status: "ready",
    supportsBatch: true,
    isLocalFirst: true,
    isPopular: true,
    maxFiles: 200,
    maxTotalSizeBytes: 1073741824,
    requiresCamera: true,
    mobileOnly: true,
    notes: ["A captura direta e mobile-first. Em navegador de computador, use importacao de imagens ou webcam quando disponivel."],
  },
  {
    id: "images-to-pdf",
    name: "Imagens para PDF",
    shortName: "Imagens para PDF",
    description: "Transforme JPG, PNG e WEBP em um unico PDF.",
    tooltip: "Use a ferramenta de camera para importar imagens e gerar PDF localmente.",
    categoryIds: ["images", "pdf"],
    aliases: ["imagem para pdf", "imagens", "jpg para pdf", "png para pdf", "webp para pdf", "image to pdf"],
    keywords: ["foto", "documentos", "galeria", "converter imagem"],
    inputExtensions: ["jpg", "jpeg", "png", "webp"],
    outputExtensions: ["pdf"],
    route: "./camera.html",
    icon: "image",
    color: "green",
    status: "ready",
    supportsBatch: true,
    isLocalFirst: true,
    isPopular: true,
    isQuickAction: true,
    notes: ["Hoje usa o fluxo de importacao de imagens da Camera para PDF."],
  },
  {
    id: "compress-image",
    name: "Comprimir imagem",
    shortName: "Comprimir imagem",
    description: "Reduza JPG, PNG, WebP e mais.",
    tooltip: "Reduza imagens localmente ajustando qualidade, formato e dimensoes.",
    categoryIds: ["images"],
    aliases: [
      "comprimir imagem",
      "compactar imagem",
      "reduzir imagem",
      "reduzir foto",
      "compress image",
      "compactar jpg",
      "compactar png",
      "compactar webp",
      "otimizar imagem",
      "otimizar foto",
      "diminuir tamanho da imagem",
    ],
    keywords: ["jpg", "jpeg", "png", "webp", "avif", "gif", "bmp", "imagem menor", "foto"],
    inputExtensions: ["jpg", "jpeg", "png", "webp", "avif", "gif", "bmp"],
    outputExtensions: ["jpg", "jpeg", "png", "webp", "avif", "zip"],
    route: "./comprimir-imagem.html",
    icon: "image-file",
    color: "blue",
    status: "ready",
    supportsBatch: true,
    isLocalFirst: true,
    isPopular: true,
    isQuickAction: true,
    browser: true,
    usesWorker: true,
    maxFiles: 500,
    maxTotalSizeBytes: 1073741824,
    maxSingleFileSizeBytes: 1073741824,
    notes: [
      "Processamento local no navegador.",
      "Arquivos nao sao enviados para servidor.",
      "Formatos disponiveis dependem do suporte do navegador.",
      "PNG usa compressao sem perdas; para reduzir mais, use redimensionamento ou converta para WebP/JPG.",
      "GIF animado pode perder animacao nesta versao.",
      "AVIF depende do suporte do navegador.",
      "Metadados EXIF geralmente sao removidos ao reprocessar no canvas.",
    ],
  },
  {
    id: "convert-image",
    name: "Converter imagem",
    shortName: "Converter imagem",
    description: "Converta entre JPG, PNG, WebP, GIF e mais.",
    tooltip: "Converta formatos de imagem localmente usando canvas e Web Worker quando disponivel.",
    categoryIds: ["images"],
    aliases: ["converter imagem", "jpg png", "png webp", "gif", "convert image"],
    keywords: ["imagem", "formato", "jpg", "png", "webp", "gif"],
    inputExtensions: ["jpg", "jpeg", "png", "webp", "gif", "bmp", "avif"],
    outputExtensions: ["jpg", "jpeg", "png", "webp", "avif", "zip"],
    route: "./comprimir-imagem.html#convert-image",
    icon: "image-plus",
    color: "orange",
    status: "ready",
    supportsBatch: true,
    isLocalFirst: true,
    isPopular: true,
    isQuickAction: true,
    browser: true,
    usesWorker: true,
    maxFiles: 500,
    maxTotalSizeBytes: 1073741824,
    notes: [
      "Usa canvas e Web Worker quando disponivel.",
      "GIF animado pode virar imagem estatica ao passar pelo canvas.",
      "AVIF depende do suporte do navegador.",
    ],
  },
  {
    id: "pdf-to-images",
    name: "PDF para imagens",
    shortName: "PDF para imagens",
    description: "Extraia paginas do PDF como imagens.",
    tooltip: "Renderizacao local de paginas PDF para JPG/PNG/WebP.",
    categoryIds: ["pdf", "images"],
    aliases: ["pdf para imagem", "pdf para jpg", "pdf para png", "pdf to image"],
    keywords: ["extrair imagem", "paginas", "jpg", "png"],
    inputExtensions: ["pdf"],
    outputExtensions: ["jpg", "png", "webp", "zip"],
    route: "./pdf-ferramentas.html#pdf-to-images",
    icon: "jpg",
    color: "teal",
    status: "beta",
    supportsBatch: false,
    isLocalFirst: true,
    isPopular: true,
    browser: true,
    usesCdn: true,
    usesWorker: true,
    notes: [
      "Usa PDF.js para renderizar paginas em canvas.",
      "PDFs grandes podem consumir memoria em DPI alto.",
    ],
  },
  {
    id: "protect",
    name: "Proteger PDF",
    shortName: "Proteger",
    description: "Adicione senha e proteja seu PDF.",
    tooltip: "Protecao por senha no navegador usando qpdf.wasm quando disponivel.",
    categoryIds: ["pdf", "security"],
    aliases: ["proteger", "senha", "security", "criptografar", "lock pdf"],
    keywords: ["pdf", "seguranca", "privado", "senha"],
    inputExtensions: ["pdf"],
    outputExtensions: ["pdf"],
    route: "./pdf-ferramentas.html#protect",
    icon: "lock",
    color: "red",
    status: "beta",
    supportsBatch: false,
    isLocalFirst: true,
    browser: true,
    usesCdn: true,
    usesWasm: true,
    heavy: true,
    notes: [
      "Usa qpdf.wasm quando a engine carrega no navegador.",
      "Nao simula senha: se a engine local falhar, nenhum PDF falso e gerado.",
      "Proteger um PDF pode invalidar assinaturas digitais existentes.",
    ],
  },
  {
    id: "unlock",
    name: "Desbloquear PDF",
    shortName: "Desbloquear",
    description: "Remova senha quando voce souber a senha.",
    tooltip: "Remocao de senha para arquivos que voce tem permissao para abrir.",
    categoryIds: ["pdf", "security"],
    aliases: ["desbloquear", "remover senha", "unlock", "tirar senha"],
    keywords: ["pdf", "senha", "seguranca"],
    inputExtensions: ["pdf"],
    outputExtensions: ["pdf"],
    route: "./pdf-ferramentas.html#unlock",
    icon: "unlock",
    color: "green",
    status: "beta",
    supportsBatch: false,
    isLocalFirst: true,
    requiresPassword: true,
    browser: true,
    usesCdn: true,
    usesWasm: true,
    heavy: true,
    notes: [
      "Requer a senha correta. Nao quebra senhas e nao faz brute-force.",
      "Usa qpdf.wasm quando a engine carrega no navegador.",
    ],
  },
  {
    id: "ocr",
    name: "OCR de PDF",
    shortName: "OCR",
    description: "Reconheca texto em PDFs escaneados.",
    tooltip: "OCR local com WASM e download sob demanda, planejado.",
    categoryIds: ["ocr", "pdf", "documents"],
    aliases: ["ocr", "texto pesquisavel", "reconhecer texto", "scan texto"],
    keywords: ["pdf", "imagem", "texto", "escaneado"],
    inputExtensions: ["pdf", "jpg", "png"],
    outputExtensions: ["txt"],
    route: "./pdf-ferramentas.html#ocr",
    icon: "search",
    color: "teal",
    status: "beta",
    supportsBatch: false,
    isLocalFirst: true,
    browser: true,
    heavy: true,
    usesCdn: true,
    usesWorker: true,
    notes: [
      "Usa Tesseract.js localmente para gerar TXT.",
      "PDF pesquisavel completo ainda nao e prometido nesta versao beta.",
      "OCR pode demorar em documentos escaneados.",
    ],
  },
  {
    id: "compress-video",
    name: "Comprimir video",
    shortName: "Comprimir video",
    description: "Reduza o tamanho de MP4, WebM e mais.",
    tooltip: "Compressao de video local com ffmpeg.wasm.",
    categoryIds: ["video"],
    aliases: ["comprimir video", "compactar mp4", "reduzir video", "compress video"],
    keywords: ["mp4", "webm", "video menor"],
    inputExtensions: ["mp4", "webm", "mov", "avi", "mkv"],
    outputExtensions: ["mp4", "webm"],
    route: "./video-ferramentas.html#compress-video",
    icon: "video",
    color: "purple",
    status: "beta",
    supportsBatch: true,
    isLocalFirst: true,
    isPopular: true,
    isQuickAction: true,
    browser: true,
    heavy: true,
    usesCdn: true,
    usesWasm: true,
    usesWorker: true,
    notes: [
      "Usa ffmpeg.wasm sob demanda.",
      "Videos grandes podem consumir muita memoria.",
      "Alguns codecs podem nao estar disponiveis no build WASM.",
    ],
  },
  {
    id: "convert-video",
    name: "Converter video",
    shortName: "Converter video",
    description: "Converta entre MP4, WebM, MOV, AVI e mais.",
    tooltip: "Conversao de video no navegador com ffmpeg.wasm.",
    categoryIds: ["video"],
    aliases: ["converter video", "mp4 webm", "mov mp4", "convert video"],
    keywords: ["mp4", "webm", "mov", "avi"],
    inputExtensions: ["mp4", "webm", "mov", "avi", "mkv", "m4v"],
    outputExtensions: ["mp4", "webm", "gif"],
    route: "./video-ferramentas.html#convert-video",
    icon: "video-convert",
    color: "orange",
    status: "beta",
    supportsBatch: true,
    isLocalFirst: true,
    browser: true,
    heavy: true,
    usesCdn: true,
    usesWasm: true,
    usesWorker: true,
    notes: [
      "Usa ffmpeg.wasm sob demanda.",
      "GIF e codecs especificos podem demorar ou falhar conforme o navegador.",
    ],
  },
  {
    id: "cut-video",
    name: "Cortar video",
    shortName: "Cortar video",
    description: "Corte trechos do video com precisao.",
    tooltip: "Edicao simples de video local com ffmpeg.wasm.",
    categoryIds: ["video"],
    aliases: ["cortar video", "recortar video", "trim video", "cut video"],
    keywords: ["mp4", "trecho", "edicao"],
    inputExtensions: ["mp4", "webm", "mov"],
    outputExtensions: ["mp4", "webm"],
    route: "./video-ferramentas.html#cut-video",
    icon: "scissors",
    color: "purple",
    status: "beta",
    supportsBatch: false,
    isLocalFirst: true,
    browser: true,
    heavy: true,
    usesCdn: true,
    usesWasm: true,
    usesWorker: true,
    notes: [
      "Corte rapido pode ser menos preciso por causa dos keyframes.",
      "Corte preciso recodifica e pode demorar mais.",
    ],
  },
  {
    id: "extract-audio",
    name: "Extrair audio",
    shortName: "Extrair audio",
    description: "Extraia o audio do video em MP3, WAV, OGG ou M4A.",
    tooltip: "Extracao de audio local com ffmpeg.wasm.",
    categoryIds: ["audio", "video"],
    aliases: ["extrair audio", "audio do video", "mp3", "wav", "extract audio"],
    keywords: ["video", "mp3", "wav", "audio"],
    inputExtensions: ["mp4", "webm", "mov", "avi", "mkv"],
    outputExtensions: ["mp3", "wav", "ogg", "m4a"],
    route: "./video-ferramentas.html#extract-audio",
    icon: "headphones",
    color: "purple",
    status: "beta",
    supportsBatch: false,
    isLocalFirst: true,
    browser: true,
    heavy: true,
    usesCdn: true,
    usesWasm: true,
    usesWorker: true,
    notes: [
      "Usa ffmpeg.wasm sob demanda.",
      "Videos sem faixa de audio retornam erro especifico da engine.",
    ],
  },
  {
    id: "convert-to-pdf",
    name: "Converter para PDF",
    shortName: "Converter para PDF",
    description: "Converta DOCX, PPTX, TXT e mais para PDF.",
    tooltip: "Conversao de documentos no navegador esta planejada para uma versao futura.",
    categoryIds: ["documents", "pdf"],
    aliases: ["converter para pdf", "word para pdf", "docx pdf", "pptx pdf"],
    keywords: ["documento", "office", "word", "powerpoint"],
    inputExtensions: ["jpg", "jpeg", "png", "webp", "avif", "txt", "md", "html", "docx"],
    outputExtensions: ["pdf"],
    route: "./pdf-ferramentas.html#convert-to-pdf",
    icon: "document",
    color: "blue",
    status: "beta",
    supportsBatch: false,
    isLocalFirst: true,
    browser: true,
    heavy: true,
    usesCdn: true,
    notes: [
      "Implementado para imagens, TXT, Markdown, HTML e DOCX simples.",
      "PPTX/XLSX complexos ainda nao sao aceitos nesta versao.",
      "Layout de DOCX pode mudar.",
    ],
  },
  {
    id: "pdf-to-word",
    name: "PDF para Word",
    shortName: "PDF para Word",
    description: "Converta PDF para DOCX editavel.",
    tooltip: "Conversao de PDF para DOCX no navegador esta no roadmap.",
    categoryIds: ["documents", "pdf"],
    aliases: ["pdf para word", "pdf to word", "pdf para docx"],
    keywords: ["documento", "docx", "word", "editar"],
    inputExtensions: ["pdf"],
    outputExtensions: ["docx"],
    route: "./pdf-ferramentas.html#pdf-to-word",
    icon: "document",
    color: "blue",
    status: "beta",
    supportsBatch: false,
    isLocalFirst: true,
    browser: true,
    heavy: true,
    usesCdn: true,
    usesWorker: true,
    notes: [
      "Modo texto usa PDF.js para extrair texto e gera DOCX basico.",
      "Modo visual renderiza paginas como imagens dentro do DOCX.",
      "Layouts complexos podem mudar.",
    ],
  },
  {
    id: "watermark",
    name: "Marca d'agua",
    shortName: "Marca d'agua",
    description: "Adicione texto ou imagem ao PDF.",
    tooltip: "Marca d'agua local para PDFs esta em desenvolvimento.",
    categoryIds: ["pdf"],
    aliases: ["marca d agua", "watermark", "marca dagua", "carimbo"],
    keywords: ["pdf", "editar", "texto", "imagem"],
    inputExtensions: ["pdf"],
    outputExtensions: ["pdf"],
    route: "./pdf-ferramentas.html#watermark",
    icon: "stamp",
    color: "purple",
    status: "ready",
    supportsBatch: false,
    isLocalFirst: true,
    browser: true,
    usesCdn: true,
    notes: [
      "Usa pdf-lib para desenhar texto ou imagem no PDF.",
      "Assinaturas digitais existentes podem ser invalidadas ao modificar o PDF.",
    ],
  },
];

export function countByStatus(tools = TOOLS) {
  return tools.reduce((acc, tool) => {
    acc[tool.status] = (acc[tool.status] || 0) + 1;
    return acc;
  }, {});
}

export function toolsInCategory(categoryId, tools = TOOLS) {
  if (categoryId === "all") return tools.slice();
  if (categoryId === "popular") return tools.filter((tool) => tool.isPopular);
  if (categoryId === "soon") return tools.filter((tool) => tool.status === "coming-soon");
  return tools.filter((tool) => (tool.categoryIds || []).includes(categoryId));
}

export function getCategory(categoryId) {
  return CATEGORIES.find((category) => category.id === categoryId) || null;
}

export function getTool(toolId, tools = TOOLS) {
  return tools.find((tool) => tool.id === toolId) || null;
}

export function readyTools(tools = TOOLS) {
  return tools.filter((tool) => tool.status === "ready");
}
