// tools/registry.js
// Catalogo central do ArqKit. Status "ready" significa rota funcional hoje.
// Ferramentas planejadas aparecem como "coming-soon" para nao simular fluxos.

export const CATEGORIES = [
  { id: "all", name: "Todas", icon: "grid" },
  { id: "popular", name: "Mais usadas", icon: "star" },
  { id: "pdf", name: "PDF", icon: "file-text" },
  { id: "images", name: "Imagens", icon: "image" },
  { id: "video", name: "Vídeo", icon: "video" },
  { id: "audio", name: "Áudio", icon: "audio" },
  { id: "documents", name: "Documentos", icon: "document" },
  { id: "security", name: "Segurança", icon: "shield" },
  { id: "ocr", name: "OCR", icon: "search" },
  { id: "soon", name: "Em breve", icon: "clock" },
];

export const STATUS_META = {
  ready: { label: "Pronto", badge: "Pronto", className: "is-ready" },
  beta: { label: "Beta", badge: "Beta", className: "is-soon" },
  "coming-soon": { label: "Em breve", badge: "Em breve", className: "is-soon" },
  "requires-desktop": { label: "Requer desktop", badge: "Desktop", className: "is-desktop" },
};

export const TOOLS = [
  {
    id: "compress",
    name: "Comprimir PDF",
    shortName: "Comprimir",
    description: "Reduza o tamanho do PDF mantendo boa qualidade.",
    tooltip: "Comprima imagens e scans dentro do PDF direto no navegador.",
    categoryIds: ["pdf"],
    aliases: ["comprimir", "compactar", "reduzir", "diminuir", "compress", "compressao", "otimizar pdf"],
    keywords: ["pdf", "leve", "tamanho", "email", "arquivo menor", "compressor"],
    inputExtensions: ["pdf"],
    outputExtensions: ["pdf"],
    route: "./comprimir-pdf.html#tool=compress",
    icon: "file-zip",
    color: "red",
    status: "ready",
    supportsBatch: false,
    isLocalFirst: true,
    isPopular: true,
    isQuickAction: true,
    notes: [],
  },
  {
    id: "merge",
    name: "Juntar PDF",
    shortName: "Juntar",
    description: "Una vários PDFs em um único arquivo.",
    tooltip: "Junte PDFs na ordem escolhida, sem enviar arquivos para servidor.",
    categoryIds: ["pdf"],
    aliases: ["juntar", "unir", "mesclar", "merge", "combinar", "combine"],
    keywords: ["pdf", "vários arquivos", "documentos", "ordem"],
    inputExtensions: ["pdf"],
    outputExtensions: ["pdf"],
    route: "./comprimir-pdf.html#tool=merge",
    icon: "link",
    color: "purple",
    status: "ready",
    supportsBatch: true,
    isLocalFirst: true,
    isPopular: true,
    isQuickAction: true,
    notes: [],
  },
  {
    id: "merge_then_compress",
    name: "Juntar e comprimir PDF",
    shortName: "Juntar + comprimir",
    description: "Una vários PDFs e reduza o tamanho ao mesmo tempo.",
    tooltip: "Gere um PDF único e comprimido em uma operação local.",
    categoryIds: ["pdf"],
    aliases: ["juntar e comprimir", "unir e comprimir", "merge and compress", "combinar e reduzir"],
    keywords: ["pdf", "compressão", "unir", "arquivo único"],
    inputExtensions: ["pdf"],
    outputExtensions: ["pdf"],
    route: "./comprimir-pdf.html#tool=merge_then_compress",
    icon: "puzzle",
    color: "green",
    status: "ready",
    supportsBatch: true,
    isLocalFirst: true,
    isPopular: true,
    notes: [],
  },
  {
    id: "split",
    name: "Dividir PDF",
    shortName: "Dividir",
    description: "Extraia páginas ou divida seu PDF em vários arquivos.",
    tooltip: "Separe páginas, intervalos ou blocos de um PDF localmente.",
    categoryIds: ["pdf"],
    aliases: ["dividir", "separar", "split", "partir", "fatiar", "extrair paginas"],
    keywords: ["pdf", "páginas", "intervalos", "organizar"],
    inputExtensions: ["pdf"],
    outputExtensions: ["pdf", "zip"],
    route: "./dividir.html",
    icon: "split",
    color: "orange",
    status: "ready",
    supportsBatch: false,
    isLocalFirst: true,
    isPopular: true,
    notes: [],
  },
  {
    id: "camera-to-pdf",
    name: "Câmera para PDF",
    shortName: "Câmera PDF",
    description: "Fotografe documentos ou importe imagens e gere um PDF.",
    tooltip: "Capture páginas pelo celular ou importe imagens para montar um PDF.",
    categoryIds: ["images", "documents"],
    aliases: ["camera", "câmera", "foto para pdf", "scan", "scanner", "digitalizar", "documento para pdf", "camera to pdf"],
    keywords: ["celular", "foto", "imagem", "documento", "scan"],
    inputExtensions: ["jpg", "jpeg", "png", "webp", "heic"],
    outputExtensions: ["pdf"],
    route: "./camera.html",
    icon: "camera",
    color: "blue",
    status: "ready",
    supportsBatch: true,
    isLocalFirst: true,
    isPopular: true,
    maxFiles: 200,
    maxTotalSizeBytes: 1073741824,
    requiresCamera: true,
    mobileOnly: true,
    notes: ["A captura direta é mobile-first. No desktop, use importação de imagens."],
  },
  {
    id: "images-to-pdf",
    name: "Imagens para PDF",
    shortName: "Imagens para PDF",
    description: "Transforme JPG, PNG e WEBP em um único PDF.",
    tooltip: "Use a ferramenta de câmera para importar imagens e gerar PDF localmente.",
    categoryIds: ["images", "pdf"],
    aliases: ["imagem para pdf", "imagens", "jpg para pdf", "png para pdf", "webp para pdf", "image to pdf"],
    keywords: ["foto", "documentos", "galeria", "converter imagem"],
    inputExtensions: ["jpg", "jpeg", "png", "webp"],
    outputExtensions: ["pdf"],
    route: "./camera.html",
    icon: "image",
    color: "green",
    status: "ready",
    supportsBatch: true,
    isLocalFirst: true,
    isPopular: true,
    isQuickAction: true,
    notes: ["Hoje usa o fluxo de importação de imagens da Câmera para PDF."],
  },
  {
    id: "compress-image",
    name: "Comprimir imagem",
    shortName: "Comprimir imagem",
    description: "Reduza JPG, PNG, WebP e mais.",
    tooltip: "Compressão de imagens local, planejada para a suite ArqKit.",
    categoryIds: ["images"],
    aliases: ["comprimir imagem", "compactar imagem", "reduzir jpg", "compress image"],
    keywords: ["jpg", "png", "webp", "imagem menor", "foto"],
    inputExtensions: ["jpg", "jpeg", "png", "webp"],
    outputExtensions: ["jpg", "png", "webp"],
    route: "#",
    icon: "image-file",
    color: "blue",
    status: "coming-soon",
    supportsBatch: true,
    isLocalFirst: true,
    isPopular: true,
    isQuickAction: true,
    notes: [],
  },
  {
    id: "convert-image",
    name: "Converter imagem",
    shortName: "Converter imagem",
    description: "Converta entre JPG, PNG, WebP, GIF e mais.",
    tooltip: "Conversão de formatos de imagem no navegador, em desenvolvimento.",
    categoryIds: ["images"],
    aliases: ["converter imagem", "jpg png", "png webp", "gif", "convert image"],
    keywords: ["imagem", "formato", "jpg", "png", "webp", "gif"],
    inputExtensions: ["jpg", "jpeg", "png", "webp", "gif"],
    outputExtensions: ["jpg", "png", "webp"],
    route: "#",
    icon: "image-plus",
    color: "orange",
    status: "coming-soon",
    supportsBatch: true,
    isLocalFirst: true,
    isPopular: true,
    isQuickAction: true,
    notes: [],
  },
  {
    id: "pdf-to-images",
    name: "PDF para imagens",
    shortName: "PDF para imagens",
    description: "Extraia páginas do PDF como imagens.",
    tooltip: "Renderização local de páginas PDF para JPG/PNG, planejada.",
    categoryIds: ["pdf", "images"],
    aliases: ["pdf para imagem", "pdf para jpg", "pdf para png", "pdf to image"],
    keywords: ["extrair imagem", "paginas", "jpg", "png"],
    inputExtensions: ["pdf"],
    outputExtensions: ["jpg", "png", "zip"],
    route: "#",
    icon: "jpg",
    color: "teal",
    status: "coming-soon",
    supportsBatch: false,
    isLocalFirst: true,
    isPopular: true,
    notes: [],
  },
  {
    id: "protect",
    name: "Proteger PDF",
    shortName: "Proteger",
    description: "Adicione senha e proteja seu PDF.",
    tooltip: "Proteção por senha no navegador está em estudo.",
    categoryIds: ["pdf", "security"],
    aliases: ["proteger", "senha", "security", "criptografar", "lock pdf"],
    keywords: ["pdf", "segurança", "privado", "senha"],
    inputExtensions: ["pdf"],
    outputExtensions: ["pdf"],
    route: "#",
    icon: "lock",
    color: "red",
    status: "coming-soon",
    supportsBatch: false,
    isLocalFirst: true,
    notes: ["Criptografia de PDF no navegador tem limitações; em estudo."],
  },
  {
    id: "unlock",
    name: "Desbloquear PDF",
    shortName: "Desbloquear",
    description: "Remova senha quando você souber a senha.",
    tooltip: "Remoção de senha para arquivos que você tem permissão para abrir.",
    categoryIds: ["pdf", "security"],
    aliases: ["desbloquear", "remover senha", "unlock", "tirar senha"],
    keywords: ["pdf", "senha", "segurança"],
    inputExtensions: ["pdf"],
    outputExtensions: ["pdf"],
    route: "#",
    icon: "unlock",
    color: "green",
    status: "coming-soon",
    supportsBatch: false,
    isLocalFirst: true,
    requiresPassword: true,
    notes: [],
  },
  {
    id: "ocr",
    name: "OCR de PDF",
    shortName: "OCR",
    description: "Reconheça texto em PDFs escaneados.",
    tooltip: "OCR local com WASM e download sob demanda, planejado.",
    categoryIds: ["ocr", "pdf", "documents"],
    aliases: ["ocr", "texto pesquisavel", "reconhecer texto", "scan texto"],
    keywords: ["pdf", "imagem", "texto", "escaneado"],
    inputExtensions: ["pdf", "jpg", "png"],
    outputExtensions: ["pdf", "txt"],
    route: "#",
    icon: "search",
    color: "teal",
    status: "coming-soon",
    supportsBatch: false,
    isLocalFirst: true,
    notes: ["Requer baixar o motor de OCR no navegador."],
  },
  {
    id: "compress-video",
    name: "Comprimir video",
    shortName: "Comprimir video",
    description: "Reduza o tamanho de MP4, WebM e mais.",
    tooltip: "Compressão de vídeo local com engine otimizada, planejada.",
    categoryIds: ["video"],
    aliases: ["comprimir video", "compactar mp4", "reduzir video", "compress video"],
    keywords: ["mp4", "webm", "video menor"],
    inputExtensions: ["mp4", "webm", "mov"],
    outputExtensions: ["mp4", "webm"],
    route: "#",
    icon: "video",
    color: "purple",
    status: "coming-soon",
    supportsBatch: true,
    isLocalFirst: true,
    isPopular: true,
    isQuickAction: true,
    notes: [],
  },
  {
    id: "convert-video",
    name: "Converter vídeo",
    shortName: "Converter vídeo",
    description: "Converta entre MP4, WebM, MOV, AVI e mais.",
    tooltip: "Conversão de vídeo no navegador está no roadmap.",
    categoryIds: ["video"],
    aliases: ["converter video", "mp4 webm", "mov mp4", "convert video"],
    keywords: ["mp4", "webm", "mov", "avi"],
    inputExtensions: ["mp4", "webm", "mov", "avi"],
    outputExtensions: ["mp4", "webm"],
    route: "#",
    icon: "video-convert",
    color: "orange",
    status: "coming-soon",
    supportsBatch: true,
    isLocalFirst: true,
    notes: [],
  },
  {
    id: "cut-video",
    name: "Cortar vídeo",
    shortName: "Cortar vídeo",
    description: "Corte trechos do vídeo com precisão.",
    tooltip: "Edição simples de vídeo local, planejada.",
    categoryIds: ["video"],
    aliases: ["cortar video", "recortar video", "trim video", "cut video"],
    keywords: ["mp4", "trecho", "edicao"],
    inputExtensions: ["mp4", "webm", "mov"],
    outputExtensions: ["mp4", "webm"],
    route: "#",
    icon: "scissors",
    color: "purple",
    status: "coming-soon",
    supportsBatch: false,
    isLocalFirst: true,
    notes: [],
  },
  {
    id: "extract-audio",
    name: "Extrair audio",
    shortName: "Extrair audio",
    description: "Extraia o áudio do vídeo em MP3 ou WAV.",
    tooltip: "Extração de áudio local, planejada.",
    categoryIds: ["audio", "video"],
    aliases: ["extrair audio", "audio do video", "mp3", "wav", "extract audio"],
    keywords: ["video", "mp3", "wav", "audio"],
    inputExtensions: ["mp4", "webm", "mov"],
    outputExtensions: ["mp3", "wav"],
    route: "#",
    icon: "headphones",
    color: "purple",
    status: "coming-soon",
    supportsBatch: false,
    isLocalFirst: true,
    notes: [],
  },
  {
    id: "convert-to-pdf",
    name: "Converter para PDF",
    shortName: "Converter para PDF",
    description: "Converta DOCX, PPTX, TXT e mais para PDF.",
    tooltip: "Conversão fiel de documentos requer recursos além de site estático.",
    categoryIds: ["documents", "pdf"],
    aliases: ["converter para pdf", "word para pdf", "docx pdf", "pptx pdf"],
    keywords: ["documento", "office", "word", "powerpoint"],
    inputExtensions: ["docx", "pptx", "txt"],
    outputExtensions: ["pdf"],
    route: "#",
    icon: "document",
    color: "blue",
    status: "requires-desktop",
    supportsBatch: false,
    isLocalFirst: false,
    requiresDesktopApp: true,
    notes: ["Conversão fiel de Office não roda de forma confiável só no navegador."],
  },
  {
    id: "pdf-to-word",
    name: "PDF para Word",
    shortName: "PDF para Word",
    description: "Converta PDF para DOCX editável.",
    tooltip: "Reconstruir layout editável de PDF exige conversor dedicado.",
    categoryIds: ["documents", "pdf"],
    aliases: ["pdf para word", "pdf to word", "pdf para docx"],
    keywords: ["documento", "docx", "word", "editar"],
    inputExtensions: ["pdf"],
    outputExtensions: ["docx"],
    route: "#",
    icon: "document",
    color: "blue",
    status: "requires-desktop",
    supportsBatch: false,
    isLocalFirst: false,
    requiresDesktopApp: true,
    notes: ["Planejado para uma variante com conversor dedicado."],
  },
  {
    id: "watermark",
    name: "Marca d'agua",
    shortName: "Marca d'agua",
    description: "Adicione texto ou imagem ao PDF.",
    tooltip: "Marca d'agua local para PDFs esta em desenvolvimento.",
    categoryIds: ["pdf"],
    aliases: ["marca d agua", "watermark", "marca dagua", "carimbo"],
    keywords: ["pdf", "editar", "texto", "imagem"],
    inputExtensions: ["pdf"],
    outputExtensions: ["pdf"],
    route: "#",
    icon: "stamp",
    color: "purple",
    status: "coming-soon",
    supportsBatch: false,
    isLocalFirst: true,
    notes: [],
  },
];

export function countByStatus(tools = TOOLS) {
  return tools.reduce((acc, tool) => {
    acc[tool.status] = (acc[tool.status] || 0) + 1;
    return acc;
  }, {});
}

export function toolsInCategory(categoryId, tools = TOOLS) {
  if (categoryId === "all") return tools.slice();
  if (categoryId === "popular") return tools.filter((tool) => tool.isPopular);
  if (categoryId === "soon") return tools.filter((tool) => tool.status !== "ready");
  return tools.filter((tool) => (tool.categoryIds || []).includes(categoryId));
}

export function getCategory(categoryId) {
  return CATEGORIES.find((category) => category.id === categoryId) || null;
}

export function getTool(toolId, tools = TOOLS) {
  return tools.find((tool) => tool.id === toolId) || null;
}

export function readyTools(tools = TOOLS) {
  return tools.filter((tool) => tool.status === "ready");
}
